### ISSUE TITLE
Consider adding "recorded_in_versions" key during import

### ISSUE THREAD

**Issue by spasovski** [mozilla/probe-search#7]
The JS implementation is at https://github.com/mozilla/probe-dictionary/blob/master/src/lib/utils.js#L152 though be wary it relies on quite a few helper functions within the same file.

With pagination in PTMO this may be less important but if we end up wanting this in both GLAM and PTMO doing the logic in one place will be better.

**Comment by robhudson** [comment]
After looking at this I think this is more display side logic and belongs where the display is.
